export class ShoppingCart {
       id:any;
       userId:any;
       productId:any;
       count:any;
       price:any;
       constructor()
       {
              this.id=null;
              this.userId=null;
              this.productId=null;
              this.count=null;
              this.price=null;
       }
}
export class DeliveryAddress{
       id:any;
       userId:any;
       address:any;
       nearBy:any;
       city:any;
       state:any;
       country:any;
       phone:any;
       alternatephoneNumber:any;
       pinCode:any;
       addressType:any;
       constructor()
       {
              this.id=null;
              this.userId=null;
              this.address=null;
              this.nearBy=null;
              this.city=null;
              this.state=null;
              this.state=null;
              this.country=null;
              this.phone=null;
              this.alternatephoneNumber=null;
              this.pinCode=null;
              this.addressType=null;
       }
     
}
export class OrderDetails{
       id:number;
       orderDate:any;
       shippingDate:any;
       orderTotal:any;
       paymentStatus:any;
       paymentDate:any;
       transactionId:any;
       deliveryAdressId:any;
       constructor(){
              this.id=0;
              this.orderDate=null;
              this.shippingDate=null;
              this.orderTotal=null;
              this.paymentStatus=null;
              this.paymentDate=null;
              this.transactionId=null;
              this.deliveryAdressId=null;
       }
}

